ktor {
  deployment {
    port: ${PORT}
    environment = ${?ENV}
  }

  application.modules: [
    dev.efemoney.lexiko.FeaturesKt.features
    dev.efemoney.lexiko.RoutesKt.routes
  ]
}

okHttp.logLevel: BASIC
