[versions]
ktor = "2.0.0-eap-342"

[libraries]
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-auth", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-locations = { module = "io.ktor:ktor-locations", version.ref = "ktor" }

ktor-server = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-plugins-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-plugins-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-plugins-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-plugins-conNeg = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-plugins-callLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-plugins-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-plugins-autoHeadResponse = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-moshi = "com.hypercubetools:ktor-moshi-server:2.1.0"

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-moshi = "com.hypercubetools:ktor-moshi-client:2.1.0"
