[versions]
coil = "2.1.0"
moshi = "1.13.0"
moshix = "0.16.6"
okio = "3.1.0"
okhttp = "5.0.0-alpha.7"
retrofit = "2.9.0"
dagger = "2.42"
glide = "4.12.0"
material = "1.5.0"
timber = "5.0.1"

[libraries]
jsr250 = "javax.annotation:jsr250-api:1.0"
turbine = "app.cash.turbine:turbine:0.8.0"
junit = "junit:junit:4.13.2"
uuid = "com.benasher44:uuid:0.4.0"
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-bom = { module = "com.squareup.okio:okio-bom", version.ref = "okio" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okHttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okHttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okHttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-lazyAdapters = "com.serjltt.moshi:moshi-lazy-adapters:2.2"

moshix-ksp = { module = "dev.zacsweers.moshix:moshi-ksp", version.ref = "moshix" }
moshix-adapters = { module = "dev.zacsweers.moshix:moshi-adapters", version.ref = "moshix" }
moshix-sealed-codegen = { module = "dev.zacsweers.moshix:moshi-sealed-codegen", version.ref = "moshix" }
moshix-sealed-runtime = { module = "dev.zacsweers.moshix:moshi-sealed-runtime", version.ref = "moshix" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-bom = { module = "io.coil-kt:coil-bom", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
